services:
    nginx:
      build: ./requirements/nginx
      volumes:
        - wordpress-data:/var/www/html
        - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - docker-network
      ports:
        - 443:443
      depends_on:
        - wordpress

    wordpress:
      build: ./requirements/wordpress
      volumes:
        - wordpress-data:/var/www/html
      networks:
        - docker-network
      environment:
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
      depends_on:
        - mariadb

    mariadb:
      build: ./requirements/mariadb
      volumes:
        - mariadb-data:/var/lib/mysql
      environment:
        - ROOT_PASSWORD=${ROOT_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
      networks:
        - docker-network
volumes:
  wordpress-data:
  mariadb-data:

networks:
  docker-network:
    name: docker-network