services:

    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        env_file:
            - ".env"
            - "./requirements/wordpress/conf/.env"
        volumes:
            - wordpress:/var/data/www
        networks:
            - docker-network
        dns:
            - 8.8.8.8
            - 1.1.1.1
        expose:
            - 9000
        restart: always
        depends_on:
            - mariadb

    nginx:
        build: ./requirements/nginx
        image: nginx
        volumes:
            - wordpress:/var/data/www
        networks:
            - docker-network
        ports:
            - 443:443
        restart: always
        env_file:
            - ".env"
            - "./requirements/mariadb/conf/.env"


    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        expose:
            - 3306
        env_file:
            - ".env"
            - "./requirements/mariadb/conf/.env"
        networks:
            - docker-network
        restart: always




networks:
    docker-network: {}

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/sgouzi/data/wordpress
            o: bind
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/sgouzi/data/mariadb
            o: bind