services:
    nginx:
      build: ./requirements/nginx
      volumes:
        - wordpress-data:/var/www/html
        - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - docker-network
      ports:
        - 443:443
      depends_on:
        - wordpress
      extra_hosts:
        - "${DOMAIN_NAME}:127.0.0.1"
    wordpress:
      build: ./requirements/wordpress
      volumes:
        - wordpress-data:/var/www/html
      networks:
        - docker-network
      environment:
        - MYSQL_DB_HOST=${MYSQL_DB_HOST}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      depends_on:
        - mariadb

    mariadb:
      build: ./requirements/mariadb
      volumes:
        - mariadb-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - docker-network
volumes:
  wordpress-data:
  mariadb-data:

networks:
  docker-network:
    name: docker-network