services:
    wordpress:
        build: ./requirements/wordpress
        env_file:
            - "./requirements/wordpress/conf/.env"
        volumes:
            - /home/sgouzi/data:/var/data/www
        networks:
            - docker-network
        dns:
            - 8.8.8.8
            - 1.1.1.1
        expose:
            - 9000
        restart: always
        depends_on:
            - mariadb

    nginx:
        build: ./requirements/nginx
        volumes:
            - /home/sgouzi/data:/var/data/www
        networks:
            - docker-network
        ports:
            - 443:443
        restart: always


    mariadb:
        build: ./requirements/mariadb
        volumes:
            - /home/sgouzi/data/mariadb:/var/lib/mysql
        expose:
            - 3306
        env_file:
            - "./requirements/mariadb/conf/.env"
        networks:
            - docker-network
        restart: always




networks:
    docker-network: {}
volumes:
    wordpress-data: {}